version: '3.7'
services:
  frontend:
    image: 200498-12703/venoxxapp:latest
    deploy:
      replicas: 1
    ports:
    - published: 5000
      target: 5000
    depends_on:
      - backend
  backend:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: venox1
volumes:
  mysql-data: